spring:
  profiles:
    active:
      - dev
---
spring:
  application:
    name: cloud-config-dev
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://http://127.0.0.1:7002/eureka/,http://http://127.0.0.1:7003/eureka/
server:
  port: 8101
---
spring:
  profiles: test
  application:
    name: cloud-config-test
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://http://127.0.0.1:7002/eureka/,http://http://127.0.0.1:7003/eureka/
server:
  port: 8102